# Development profile
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Optional datasource example (uncomment to use)
# Let the connector create the database if it doesn't exist
#spring.datasource.url=jdbc:mysql://localhost:3306/secondhand_fashion_marketplace?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=

# Optional: run SQL files from classpath on startup
# Place `schema.sql` and `data.sql` in `src/main/resources/` to have Spring execute them
#spring.sql.init.mode=always
#spring.sql.init.platform=mysql

# If you prefer Hibernate to manage schema, keep `spring.jpa.hibernate.ddl-auto=update` (already set above)

ghn.api.base-url=https://dev-online-gateway.ghn.vn/shiip/public-api
ghn.api.token=db44e853-cc14-11ef-b1ed-769685acafa5
ghn.api.shop-id=2509459

