spring.application.name=be

# Active profile should be supplied via SPRING_PROFILES_ACTIVE when needed.

# Database
spring.datasource.url=jdbc:mysql://146.190.93.192:3306/secondhand_fashion_marketplace?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Upload files
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Executor for Cloudflare image uploads
executor.image-upload.core-pool-size=4
executor.image-upload.max-pool-size=8
executor.image-upload.queue-capacity=100
executor.image-upload.keep-alive-seconds=60

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Cloudflare R2
# Sửa đoạn này từ biến ${...} thành giá trị thật bạn đã copy từ .env
cloudflare.r2.account-id=9d00de951bfd9979b31532e1d1033be2
cloudflare.r2.access-key=751c1daf4c2a6b3fb539442d0791f934
cloudflare.r2.secret-key=5e4453af386dd1d86c44c7bdbdb9226bfeb9f5188d6dbd5c0a0916508530e8e6
cloudflare.r2.bucket-name=secondhand-fashion-marketplace-images
cloudflare.r2.domain=https://pub-ec6ce4b499b744d3b69073c533adf28d.r2.dev

# Giữ nguyên dòng này vì nó sẽ tự ghép ID ở trên vào
cloudflare.r2.endpoint=https://${cloudflare.r2.account-id}.r2.cloudflarestorage.com

# Java Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tailam164@gmail.com
spring.mail.password=xxslfhfwvnkiiscn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# Frontend URL Configuration
app.frontend-url=${APP_FRONTEND_URL:http://localhost:3000}

# VNPay Gateway Configuration
vnpay.pay-url=${VNP_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnpay.return-url=${VNP_RETURN_URL:http://localhost:8080/api/vnpayment/return}
vnpay.tmn-code=${VNP_TMN_CODE:JGV9MSIF}
vnpay.secret-key=${VNP_SECRET_KEY:E9QLQ1W7KCLQKQLE5522R5JNRR7WIV8I}
